<!--
  版权所有：bilibili月が綺麗ですね_
  SPDX-License-Identifier: LicenseRef-Shiori-Engine
  作者：bilibili月が綺麗ですね_
  Shiori Engine - Open Source Visual Novel Engine

  本引擎采用宽松开源协议，允许用户根据项目需求自由修改、定制和发布衍生作品。
  使用时请保留上述版权声明，具体授权条款详见 license.txt 文件。

  Shiori 启动器 — 项目配置文件
-->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition=" '$(Configuration)' == 'Debug' ">Exe</OutputType>
    <OutputType Condition=" '$(Configuration)' == 'Release' ">WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>ico\ico256.ico</ApplicationIcon>
    <RootNamespace>ShioriCSharp</RootNamespace>
    <AssemblyName Condition=" '$(Configuration)' == 'Debug' ">Shiori_debug</AssemblyName>
    <AssemblyName Condition=" '$(Configuration)' == 'Release' ">Shiori</AssemblyName>
    <Version>1.2.5.0</Version>
    <Company>bilibili @月が綺麗ですね_</Company>
    <Authors>bilibili @月が綺麗ですね_</Authors>
    <Product>Shiori Engine Launcher</Product>
    <Description>Shiori 引擎启动器</Description>
    <Copyright>Copyright © 2026 bilibili @月が綺麗ですね_</Copyright>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishDir Condition=" '$(Platform)' == 'AnyCPU' ">dist\</PublishDir>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2365.46" />
    <PackageReference Include="OpenCvSharp4" Version="4.9.0.20240103" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.9.0.20240103" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ico\*.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
